import bengkelpakmuh.JasaBengkel
import bengkelpakmuh.Pelanggan
import bengkelpakmuh.Transaksi
import bengkelpakmuh.Worker

class BootStrap {

    def init = { servletContext ->

        Worker tambahworker1= new Worker(namaWorker: "ahnaf")
        tambahworker1.save()
        Worker tambahworker2 = new Worker(namaWorker: "fudol")
        tambahworker2.save()
        Worker tambahworker3= new Worker(namaWorker: "rahma")
        tambahworker3.save()
        Worker tambahworker4 = new Worker(namaWorker: "widi")
        tambahworker4.save()
        Worker tambahworker5= new Worker(namaWorker: "juli")
        tambahworker5.save()

        Pelanggan tambahpelanggan1 = new Pelanggan(namapelanggan: "bapakahnaf", platmobil: "DD123AA", nomorwa: "082280555123")
        tambahpelanggan1.save()
        Pelanggan tambahpelanggan2 = new Pelanggan(namapelanggan: "bapakfudol", platmobil: "DD124AA", nomorwa: "082280555124")
        tambahpelanggan2.save()
        Pelanggan tambahpelanggan3 = new Pelanggan(namapelanggan: "bapakrahma", platmobil: "DD125AA", nomorwa: "082280555125")
        tambahpelanggan3.save()
        Pelanggan tambahpelanggan4 = new Pelanggan(namapelanggan: "bapakwidi", platmobil: "DD126AA", nomorwa: "082280555126")
        tambahpelanggan4.save()
        Pelanggan tambahpelanggan5 = new Pelanggan(namapelanggan: "bapakjuli", platmobil: "DD127AA", nomorwa: "082280555127")
        tambahpelanggan5.save()

        JasaBengkel tambahjasa1= new JasaBengkel(namajasa: "ganti oli biasa", hargaJasa: 30000, durasiKerja: 30)
        tambahjasa1.save()
        JasaBengkel tambahjasa2= new JasaBengkel(namajasa: "service ringan", hargaJasa: 30000, durasiKerja: 60)
        tambahjasa2.save()
        JasaBengkel tambahjasa3= new JasaBengkel(namajasa: "ganti oli", hargaJasa: 40000, durasiKerja: 15)
        tambahjasa3.save()
        JasaBengkel tambahjasa4= new JasaBengkel(namajasa: "ganti velg", hargaJasa: 35000, durasiKerja: 30)
        tambahjasa4.save()
        JasaBengkel tambahjasa5= new JasaBengkel(namajasa: "ganti lampu", hargaJasa: 15000, durasiKerja: 20)
        tambahjasa5.save()

        Transaksi tambahtransaksi1=new Transaksi(nomortransaksi: "123", totaldurasi: 60, totalharga: 100000, pelanggan: tambahpelanggan1)
                .addToServices(tambahjasa1)
                .addToServices(tambahjasa3)
                .addToWorkers(tambahworker2)
        tambahtransaksi1.save()
        Transaksi tambahtransaksi2=new Transaksi(nomortransaksi: "124", totaldurasi: 70, totalharga: 1120000, pelanggan: tambahpelanggan2)
                .addToServices(tambahjasa1)
                .addToServices(tambahjasa3)
                .addToWorkers(tambahworker1)
        tambahtransaksi2.save()
        Transaksi tambahtransaksi3=new Transaksi(nomortransaksi: "125", totaldurasi: 40, totalharga: 13000, pelanggan: tambahpelanggan3)
                .addToServices(tambahjasa2)
                .addToServices(tambahjasa5)
                .addToServices(tambahjasa5)
                .addToWorkers(tambahworker3)
        tambahtransaksi3.save()
        Transaksi tambahtransaksi4=new Transaksi(nomortransaksi: "126", totaldurasi: 170, totalharga: 300000, pelanggan: tambahpelanggan4)
                .addToServices(tambahjasa3)
                .addToServices(tambahjasa2)
                .addToWorkers(tambahworker4)
        tambahtransaksi4.save()
        Transaksi tambahtransaksi5=new Transaksi(nomortransaksi: "127", totaldurasi: 560, totalharga: 400000, pelanggan: tambahpelanggan4)
                .addToServices(tambahjasa4)
                .addToServices(tambahjasa5)
                .addToWorkers(tambahworker5)
        tambahtransaksi5.save()
        Transaksi tambahtransaksi6=new Transaksi(nomortransaksi: "128", totaldurasi: 30, totalharga: 1460000, pelanggan: tambahpelanggan5)
                .addToServices(tambahjasa5)
                .addToServices(tambahjasa1)
                .addToWorkers(tambahworker2)
        tambahtransaksi6.save()
        Transaksi tambahtransaksi7=new Transaksi(nomortransaksi: "129", totaldurasi: 20, totalharga: 1045000, pelanggan: tambahpelanggan1)
                .addToServices(tambahjasa1)
                .addToServices(tambahjasa2)
                .addToWorkers(tambahworker1)
        tambahtransaksi7.save()
        Transaksi tambahtransaksi8=new Transaksi(nomortransaksi: "130", totaldurasi: 900, totalharga: 12000, pelanggan: tambahpelanggan2)
                .addToServices(tambahjasa2)
                .addToServices(tambahjasa4)
                .addToWorkers(tambahworker4)
        tambahtransaksi8.save()
        Transaksi tambahtransaksi9=new Transaksi(nomortransaksi: "131", totaldurasi: 400, totalharga: 320000, pelanggan: tambahpelanggan3)
                .addToServices(tambahjasa2)
                .addToServices(tambahjasa3)
                .addToWorkers(tambahworker5)
        tambahtransaksi9.save()
        Transaksi tambahtransaksi10=new Transaksi(nomortransaksi: "132", totaldurasi: 300, totalharga: 300000, pelanggan: tambahpelanggan5)
                .addToServices(tambahjasa1)
                .addToServices(tambahjasa5)
                .addToWorkers(tambahworker2)
        tambahtransaksi10.save()

    }
    def destroy = {
    }
}
